services:
  app:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: