"""create all tables

Revision ID: d73a60e07260
Revises: 
Create Date: 2025-05-14 14:22:11.310671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73a60e07260'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_discs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description_2p_set', sa.String(), nullable=True),
    sa.Column('description_4p_set', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_discs_id'), 'drive_discs', ['id'], unique=False)
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_id'), 'factions', ['id'], unique=False)
    op.create_table('w_engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('specialty', sa.Enum('DEFENSE', 'ANOMALY', 'ATTACK', 'STUN', 'SUPPORT', 'RUPTURE', name='specialty'), nullable=False),
    sa.Column('effect', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_w_engines_id'), 'w_engines', ['id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('specialty', sa.Enum('DEFENSE', 'ANOMALY', 'ATTACK', 'STUN', 'SUPPORT', 'RUPTURE', name='specialties'), nullable=False),
    sa.Column('attribute', sa.Enum('ELECTRIC', 'ETHER', 'FIRE', 'FROST', 'ICE', 'PHYSICAL', name='attributes'), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('version_released', sa.Float(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('bangboo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('version_released', sa.Float(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bangboo_id'), 'bangboo', ['id'], unique=False)
    op.create_table('mindscapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mindscapes_id'), 'mindscapes', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('AGENT_BASIC_ATTACK', 'AGENT_DODGE', 'AGENT_ASSIST', 'AGENT_SPECIAL_ATTACK', 'AGENT_CHAIN_ATTACK', 'AGENT_CORE_SKILL', 'BANGBOO_ACTIVE_SKILL', 'BANGBOO_ADDITIONAL_SKILL', 'BANGBOO_CHAIN_ATTACK', name='skill_type'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('bangboo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['bangboo_id'], ['bangboo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stats', sa.Enum('FLAT_ATK', 'PERCENT_ATK', 'BASE_ATK', 'FLAT_HP', 'PERCENT_HP', 'FLAT_DEF', 'PERCENT_DEF', 'PEN_RATIO', 'PEN', 'CRIT_RATE', 'CRIT_DMG', 'ANOMALY_PROFICIENCY', 'ANOMALY_MASTERY', 'IMPACT', 'ENERGY_REGEN', 'PHYSICAL_DMG', 'FIRE_DMG', 'ICE_DMG', 'ELECTRIC_DMG', 'ETHER_DMG', name='stats_type'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('bangboo_id', sa.Integer(), nullable=True),
    sa.Column('base_stats_id', sa.Integer(), nullable=True),
    sa.Column('advanced_stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advanced_stats_id'], ['w_engines.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['bangboo_id'], ['bangboo.id'], ),
    sa.ForeignKeyConstraint(['base_stats_id'], ['w_engines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_id'), 'stats', ['id'], unique=False)
    op.create_table('voice_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_actors_id'), 'voice_actors', ['id'], unique=False)
    op.create_table('skills_multipliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_multipliers_id'), 'skills_multipliers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_multipliers_id'), table_name='skills_multipliers')
    op.drop_table('skills_multipliers')
    op.drop_index(op.f('ix_voice_actors_id'), table_name='voice_actors')
    op.drop_table('voice_actors')
    op.drop_index(op.f('ix_stats_id'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_mindscapes_id'), table_name='mindscapes')
    op.drop_table('mindscapes')
    op.drop_index(op.f('ix_bangboo_id'), table_name='bangboo')
    op.drop_table('bangboo')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_w_engines_id'), table_name='w_engines')
    op.drop_table('w_engines')
    op.drop_index(op.f('ix_factions_id'), table_name='factions')
    op.drop_table('factions')
    op.drop_index(op.f('ix_drive_discs_id'), table_name='drive_discs')
    op.drop_table('drive_discs')
    # ### end Alembic commands ###
